// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3RpAPk_SQ67fpNYD6ACD1cZmoPb8r_0E',
    appId: '1:561664063651:web:ff377bb762d88ea3a96716',
    messagingSenderId: '561664063651',
    projectId: 'news-beb59',
    authDomain: 'news-beb59.firebaseapp.com',
    storageBucket: 'news-beb59.appspot.com',
    measurementId: 'G-ZEC572QSK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXuJf4E41YifjN6jfmbb81ESvzf_CXf_k',
    appId: '1:561664063651:android:421dd8ef316e6d27a96716',
    messagingSenderId: '561664063651',
    projectId: 'news-beb59',
    storageBucket: 'news-beb59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwA1EJOMAcv4gBwpRzHf8R20cvYBlD8iA',
    appId: '1:561664063651:ios:8210e50eb71484b7a96716',
    messagingSenderId: '561664063651',
    projectId: 'news-beb59',
    storageBucket: 'news-beb59.appspot.com',
    androidClientId: '561664063651-qbp8jk0h87dmooktg0vfb0u7e37m7av0.apps.googleusercontent.com',
    iosClientId: '561664063651-arkg9km3trism452djqomu31du5cls1i.apps.googleusercontent.com',
    iosBundleId: 'com.company.docFire',
  );
}
